export const libraryData = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
  },
  { id: 2, title: "1984", author: "George Orwell", genre: "Dystopian" },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
  },
  { id: 5, title: "The Hobbit", author: "J.R.R. Tolkien", genre: "Fantasy" },
  {
    id: 6,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
  },
  { id: 8, title: "Animal Farm", author: "George Orwell", genre: "Satire" },
  {
    id: 9,
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
  },
  {
    id: 10,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
  },
  {
    id: 11,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Science Fiction",
  },
  {
    id: 12,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    genre: "Historical Fiction",
  },
  {
    id: 13,
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Gothic Fiction",
  },
  {
    id: 14,
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    genre: "Autobiography",
  },
  {
    id: 15,
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    genre: "Mystery",
  },
  {
    id: 16,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Dystopian",
  },
  {
    id: 17,
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    genre: "Historical Fiction",
  },
  {
    id: 18,
    title: "The Fault in Our Stars",
    author: "John Green",
    genre: "Young Adult",
  },
  { id: 19, title: "Gone Girl", author: "Gillian Flynn", genre: "Mystery" },
  {
    id: 20,
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    genre: "Mystery",
  },
  { id: 21, title: "The Shining", author: "Stephen King", genre: "Horror" },
  {
    id: 22,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    genre: "Fantasy",
  },
  {
    id: 23,
    title: "The Giver",
    author: "Lois Lowry",
    genre: "Science Fiction",
  },
  {
    id: 24,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    genre: "Fantasy",
  },
  {
    id: 25,
    title: "The Maze Runner",
    author: "James Dashner",
    genre: "Science Fiction",
  },
  { id: 26, title: "The Road", author: "Cormac McCarthy", genre: "Dystopian" },
  {
    id: 27,
    title: "The Outsiders",
    author: "S.E. Hinton",
    genre: "Young Adult",
  },
  {
    id: 28,
    title: "The Help",
    author: "Kathryn Stockett",
    genre: "Historical Fiction",
  },
  {
    id: 29,
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    genre: "Dystopian",
  },
  {
    id: 30,
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    genre: "Fantasy",
  },
  {
    id: 31,
    title: "The Chronicles of Narnia: Prince Caspian",
    author: "C.S. Lewis",
    genre: "Fantasy",
  },
  {
    id: 32,
    title: "The Road Less Traveled",
    author: "M. Scott Peck",
    genre: "Self-Help",
  },
  { id: 33, title: "The Da Vinci Code", author: "Dan Brown", genre: "Mystery" },
  { id: 34, title: "The Hobbit", author: "J.R.R. Tolkien", genre: "Fantasy" },
  {
    id: 35,
    title: "The Time Traveler's Wife",
    author: "Audrey Niffenegger",
    genre: "Science Fiction",
  },
  {
    id: 36,
    title: "The Perks of Being a Wallflower",
    author: "Stephen Chbosky",
    genre: "Young Adult",
  },
  {
    id: 37,
    title: "The Night Circus",
    author: "Erin Morgenstern",
    genre: "Fantasy",
  },
  {
    id: 38,
    title: "The Help",
    author: "Kathryn Stockett",
    genre: "Historical Fiction",
  },
  {
    id: 39,
    title: "The Goldfinch",
    author: "Donna Tartt",
    genre: "Contemporary Fiction",
  },
  {
    id: 40,
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    genre: "Historical Fiction",
  },
  {
    id: 41,
    title: "The Maze Runner",
    author: "James Dashner",
    genre: "Science Fiction",
  },
  { id: 42, title: "The Bell Jar", author: "Sylvia Plath", genre: "Classic" },
  {
    id: 43,
    title: "The Book Thief",
    author: "Markus Zusak",
    genre: "Historical Fiction",
  },
  {
    id: 44,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Science Fiction",
  },
  {
    id: 45,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
  },
  {
    id: 46,
    title: "The Giver",
    author: "Lois Lowry",
    genre: "Science Fiction",
  },
  { id: 47, title: "The Road", author: "Cormac McCarthy", genre: "Dystopian" },
  {
    id: 48,
    title: "The Outsiders",
    author: "S.E. Hinton",
    genre: "Young Adult",
  },
  {
    id: 49,
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    genre: "Dystopian",
  },
  {
    id: 50,
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    genre: "Fantasy",
  },
];
